name: ${project.name}
version: ${project.version}
author: totemo
authors: []
description: ${project.description}
website: ${project.url}
main: nu.nerd.df.DragonFight
api-version: 1.15
depend: [BeastMaster]

permissions:
  dragonfight.console:
    description: Permission to use admininstrative commands that require console access.
    default: op

  dragonfight.admin:
    description: Permission to administer fights.
    default: op

  dragonfight.user:
    description: Permission to administer fights.
    default: true

commands:
  dragonfight:
    description: ${project.name} administrative command.
    permission: dragonfight.console
    usage: |

      §5/<command> help§f - Show this help. Equivalent to §5/help /<command>§f.
      §5/<command> reload§f - Reload the configuration.

  df:
    description: ${project.name} administrative command.
    permission: dragonfight.admin
    usage: |

      §5/<command> help§f - Show this help. Equivalent to §5/help /<command>§f.
      §5/<command> info§f - Show information about the current fight: stage number, owner, boss health and dragon health.
      §5/<command> stop§f - Stop the current fight.
      §5/<command> next§f - Kill the current boss, skipping to the next stage.
      §5/<command> stage <number>§f - Skip forward to the specified stage, from 0 to 11 (dragon only).
      §5/<command> owner <player>§f - Set the owner of the current fight.
      §5/<command> unclaimed§f - List players with unclaimed prizes.
      §5/<command> list§f - List all 10 stage titles and subtitles.
      §5/<command> swap <from> <to>§f - Swap two stages by stage number (1 to 10).
      §5/<command> move <from> <to>§f - Move stage <from> to stage <to> and shift in-between stages into the gap.
      §5/<command> config <stage>§f - Show the configuration of <stage> 1 to 10.
      §5/<command> config <stage> barcolor <color>§f - Configure stage bar color.
      §5/<command> config <stage> title <text>§f - Configure stage title.
      §5/<command> config <stage> subtitle <text>§f - Configure stage subtitle.
      §5/<command> config <stage> message <text>§f - Configure stage message.

  dragon:
    description: ${project.name} player command.
    permission: dragonfight.user
    usage: |

      §5/<command> help§f - Show this help. Equivalent to §5/help /<command>§f.
      §5/<command> info§f - Show information about the current fight: stage number, owner.
      §5/<command> prize§f - Claim one prize for defeating the dragon.

